import NavBar from './components/characters/navbar/NavBar'
import './globals.css'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-gradient-to-r from-[#094293] via-[#6048ff] to-[#094293] `}
      >
        <NavBar />
        <div className="  bg-black/50">
          <div className="w-[90%] m-auto max-w-screen-lg pt-20">{children}</div>
        </div>
      </body>
    </html>
  )
}
